export 'package:flutter/material.dart';
export 'package:learnify_app/config/Components/bottom_navigation_bar.dart';
export 'package:learnify_app/config/routes/route_names.dart';
export 'package:learnify_app/views/auth_view/login/login.dart';
export 'package:learnify_app/views/auth_view/signUp/signup.dart';
export 'package:learnify_app/views/home_screen/home_screen.dart';
export 'package:learnify_app/views/profile/profile_screen.dart';
export 'package:learnify_app/views/splashScreen/splash_screen.dart';
export 'package:learnify_app/views/playlist/playlist.dart';